engines:
  pep8:
    enabled: true	
    checks:
      # Line break before binary operator
      W503:
        enabled: false
  radon: 
    enabled: true
ratings:
  paths:
    - "mafipy/**"
    - "*.py"
exclude_paths:
  - "examples/*"
  - "ci/*"

