language: python
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
env:
  global:
  # CODECLIMATE_REPO_TOKEN=<token>
  - secure: EbvVQBNICJ3KY3S/8tuJYvAQaieNNyL1w+NrMKgHSziHlplXv26c8SDWx/F/GMv12LIfx52kiiiJBGEbQ2aKICNfpaIjr4TEHolCJbFMYP/alkS0j3UYvYoUz+Dl/SAsyQxN+lCF9LOe0o/+UoaSOm2fi6ef38cmegXZvErwiD4i1iyx+FMug92qq4bB9lG+pnGt3+z7amR9A22h5d+XADIRQDzEHATYz2annSq+umhLTpme0BudXqZiUHvFyhXFchlqmX1lCeCF4FOTgpi/7FAJqZ6KcmeGl5gwG52dSpToJpNGOs9/afUudcaN0zmKSz9vAwiZnTyfZtjXItgwVOoTjz8kD5674u69Tec2HOd8Bh0bD9ApMW2geG38XFftncl8Ul68fPdCoXga3VqbquC+iu/oEEmOsNYBBjgl//AuxqOmseWhchNnu0qEeo/YlSFoX++/9yjqd/9jgnjIaJuHsbwHCa0pxEZuYzrgVOoN2Hq5+a3iW5TgsPlWeFKMBYfPPmKVAgadlgrJ4V+xskTyQ4vjfymj6yFgV0NgHLfPimfQprqv1XE8F3l5Zk1kJhKxJR+6NXB+WN1bpKiTrQAu2TcawaEopbfH23+2pM7kuglOwsIESAeJ/gb7ud17P3AnTRY9L5x5n78wFsSb/yLG/xt4IRLyjPCC6/gNixg=
matrix:
  include:
  - python: '2.7'
    env:
    - COVERAGE="true"
    - SKIP_TESTS="false"
    - CODECLIMATE_COVERAGE_REPORT="false"
  - python: '3.5'
    env:
    - COVERAGE="true"
    - SKIP_TESTS="false"
    - CODECLIMATE_COVERAGE_REPORT="true"
before_install:
- pwd
- ls -la
- echo ${PATH}
- python --version
install: bash ci/travis/install.sh
script: python setup.py test
after_success: bash ci/travis/after_success.sh
notifications:
  slack:
    secure: i9zIk/OgAtjR9Vlnr0qJT93lfSH3uGTH47gUrYkCaD4PGWExSgPomWAsl2UYBBvcn3spQb7zENWPLaNU+0h71+OcnDUWdjoQx8wpEx7aRo8XWibkKjK0axMfxco0KoTDcV84y4QDLysY/P4M1YvLuVRCd64yUlYxv+V4aHC5CzjiXbtKa1IqP4RZqYi0gCG5QFHK776O3Btt1V4PyLOocHvy5cUY8TzWO40vDExuYSpfB0hWwuXuCxgpezifh4Ed5yjVZ8A2SpCYjYjj1ZWxnwJ9uWSQpe77rYuPAs2M0f652lcK7IVh9cIKNMsjgPcqY0F2VuDF5lpwqAYv7Mw1rhj76UVXgaUXvqcPUulUvMraUJYYXUPUNegKufocZfdKm2AZlMknQzYUblHz4G3rf6XDv8Mm5KdQJdapYouCLVbrEPsR/IIJAeNRb/gSJwlWRGc98xdoviqLUW+lsoJrI5P4Xvp039B8UqyecossNazaP/fv3JnVYgpX6vws1d79PmHtILwOwRdb5LI//zaiieu8sTLfRJxR1FQixQ7rUIittHFtckw14W3jUKLVFeuL+9vAidOEVd4ok0trKAcFqEVvXLU5xXytBVlkX3txyh2Bi/0pazEeGGhDYDLabEq2LhX9uL367KB41Up7UF+Qo3tqaGQqtzICdelXdUSz5H0=
