language: python
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
env:
  global:
  - secure: Bob5tCa0d/vBzlgu5gfU66jn9dS9ugWURv9QtYeSf9COAG43UG7LnIDUzRg1STsGj5fDVScOSjdnQemVCELGgbIv8yweCYD64QeGjKje7M3x6dssKbg7vdXaWj2+2PLMTbATu3fq3dRaByEjDlBXgiA7TN9e3GelfkFSRdenXf2HArxegVY96SKP1ggCBg0H2DOjNDYnNH05Nv8W/HMbgf8IK/SdUk9zr63xF2LXgBLnnhaf12veFipkIMiLUen0xEaquRPpbFewCzm1tGFGdHQ73Hrh0f+m6N6ByMLDA3PVPJfoPsjAdXziFxAZnJf+GauuxZ6+O9+kzesot0Lwqr/mZMTKe6QnJw/nQ6MwREmPueLNVAvMBVe/Jw6Ep/m/9KMoQEZP83Ch05Tq9inlIzT6i/6KszJ8mxsoOPSDxBvG5ZxgbIYTndB0lsx3idaBd27gqBdUG/YNvbFnzdR8/nxTvCDoSMS7gSfNtI9ISRn3r++ysMEJ7fCQWs/Cm+Arein/n/3lvfIs8WS3FBPyANu5tAyFZHxLYreQ5/LuYbmXHP1yp+1Qvk09/N5QOAlQuZ1ZY2opgN5LyzuiHavtDxvivh4Mo8/In7Nl+Qqx9xWNtQC3I6FncyhTpNh44JF9s8HhKdiOsEapz8z4RIbCTCIg4HKxXNAiR109hcgUBwE=
matrix:
  include:
  - python: '2.7'
    env:
    - COVERAGE="true"
    - SKIP_TESTS="false"
    - CODECLIMATE_COVERAGE_REPORT="false"
  - python: '3.5'
    env:
    - COVERAGE="true"
    - SKIP_TESTS="false"
    - CODECLIMATE_COVERAGE_REPORT="true"
before_install:
- pwd
- ls -la
- echo ${PATH}
- python --version
install: bash ci/travis/install.sh
script: python setup.py test
after_success: bash ci/travis/after_success.sh
notifications:
  slack:
    secure: i9zIk/OgAtjR9Vlnr0qJT93lfSH3uGTH47gUrYkCaD4PGWExSgPomWAsl2UYBBvcn3spQb7zENWPLaNU+0h71+OcnDUWdjoQx8wpEx7aRo8XWibkKjK0axMfxco0KoTDcV84y4QDLysY/P4M1YvLuVRCd64yUlYxv+V4aHC5CzjiXbtKa1IqP4RZqYi0gCG5QFHK776O3Btt1V4PyLOocHvy5cUY8TzWO40vDExuYSpfB0hWwuXuCxgpezifh4Ed5yjVZ8A2SpCYjYjj1ZWxnwJ9uWSQpe77rYuPAs2M0f652lcK7IVh9cIKNMsjgPcqY0F2VuDF5lpwqAYv7Mw1rhj76UVXgaUXvqcPUulUvMraUJYYXUPUNegKufocZfdKm2AZlMknQzYUblHz4G3rf6XDv8Mm5KdQJdapYouCLVbrEPsR/IIJAeNRb/gSJwlWRGc98xdoviqLUW+lsoJrI5P4Xvp039B8UqyecossNazaP/fv3JnVYgpX6vws1d79PmHtILwOwRdb5LI//zaiieu8sTLfRJxR1FQixQ7rUIittHFtckw14W3jUKLVFeuL+9vAidOEVd4ok0trKAcFqEVvXLU5xXytBVlkX3txyh2Bi/0pazEeGGhDYDLabEq2LhX9uL367KB41Up7UF+Qo3tqaGQqtzICdelXdUSz5H0=
