defaults: &defaults
  working_directory: /root/project
  environment:
    - BENCHMARK_TEST: "true"
  docker:
    - image: "i05nagai/mafipy-python36:latest"

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
              pwd
              ls -la
              echo ${PATH}
              python --version
              git submodule sync
              git submodule update --init
              bash ci/circle_ci/dependencies.sh
              bash ci/circle_ci/test.sh
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is taken to be the root directory of the workspace.
          root: /root
          # Must be relative path from root
          paths:
            - project

  deployment:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          command: |
              pwd
              ls -la
              ls -la /root/project
              bash ci/circle_ci/deployment.sh /root/project
      - add_ssh_keys:
          fingerprints:
            - "bd:66:6a:e6:b5:9b:69:80:7e:b2:b6:91:3e:69:75:8b"
workflows:
  version: 2
  default:
    jobs:
      - test
      - deployment:
          filters:
            branches:
              only:
                - master
          requires:
            - test
